Travis CI
About Us
 
Blog
 
Status
 
Documentation
 Sign in with GitHub
Help make Open Source a better place and start building better software today!

rg3 / youtube-dl
 build:passed
Current
 
Branches
 
Build History
 
Pull Requests
 
Build #16435
 
Job #16435.7
 More options
 master [frontendmasters] Fix issues and improve extraction (closes #3661, closes #16328)
 Commit 49128b5 
 Compare 4742150..49128b5 
 Branch master 
 Sergey M. avatar Sergey M.

 #16435.7 failed
 Ran for 30 sec
 4 months ago
 Python: 3.6
YTDL_TEST_SET=core
Job log
 
View config
 Raw log
worker_info
Worker information
hostname: eb9237c1-e7df-4d80-9bd5-16ab6f7b2d6e@1.i-06b4cce-production-2-worker-org-ec2.travisci.net
version: v3.10.0 https://github.com/travis-ci/worker/tree/fe0fc6b62205b7548599ce4537c49ead63122c38
instance: 422611a travisci/ci-garnet:packer-1512502276-986baf0 (via amqp)
startup: 376.0873ms
system_info
Build system information
Build language: python
Build group: stable
Build dist: trusty
Build id: 401267130
Job id: 401267137
Runtime kernel version: 4.14.12-041412-generic
travis-build version: e2a995511
Build image provisioning date and time
Tue Dec  5 20:11:19 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Cookbooks Version
7c2c6a6 https://github.com/travis-ci/travis-cookbooks/tree/7c2c6a6
git version
git version 2.15.1
bash version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
gcc version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64
clang version
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-5.0.0/bin
jq version
jq-1.5
bats version
Bats 0.4.0
shellcheck version
0.4.6
shfmt version
v2.0.0
ccache version
ccache version 3.1.9
Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2011 Joel Rosdahl
This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.
cmake version
cmake version 3.9.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
heroku version
heroku-cli/6.14.39-addc925 (linux-x64) node-v9.2.0
imagemagick version
Version: ImageMagick 6.7.7-10 2017-07-31 Q16 http://www.imagemagick.org
md5deep version
4.2
mercurial version
Mercurial Distributed SCM (version 4.2.2)
(see https://mercurial-scm.org for more information)
Copyright (C) 2005-2017 Matt Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
mysql version
mysql  Ver 14.14 Distrib 5.6.33, for debian-linux-gnu (x86_64) using  EditLine wrapper
openssl version
OpenSSL 1.0.1f 6 Jan 2014
packer version
Packer v1.0.2
Your version of Packer is out of date! The latest version
is 1.1.2. You can update by downloading from www.packer.io
postgresql client version
psql (PostgreSQL) 9.6.6
ragel version
Ragel State Machine Compiler version 6.8 Feb 2013
Copyright (c) 2001-2009 by Adrian Thurston
subversion version
svn, version 1.8.8 (r1568071)
   compiled Aug 10 2017, 17:20:39 on x86_64-pc-linux-gnu
Copyright (C) 2013 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/
The following repository access (RA) modules are available:
* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.3
  - handles 'http' scheme
  - handles 'https' scheme
sudo version
Sudo version 1.8.9p5
Configure options: --prefix=/usr -v --with-all-insults --with-pam --with-fqdn --with-logging=syslog --with-logfac=authpriv --with-env-editor --with-editor=/usr/bin/editor --with-timeout=15 --with-password-timeout=0 --with-passprompt=[sudo] password for %p:  --without-lecture --with-tty-tickets --disable-root-mailer --enable-admin-flag --with-sendmail=/usr/sbin/sendmail --with-timedir=/var/lib/sudo --mandir=/usr/share/man --libexecdir=/usr/lib/sudo --with-sssd --with-sssd-lib=/usr/lib/x86_64-linux-gnu --with-selinux
Sudoers policy plugin version 1.8.9p5
Sudoers file grammar version 43
Sudoers path: /etc/sudoers
Authentication methods: 'pam'
Syslog facility if syslog is being used for logging: authpriv
Syslog priority to use when user authenticates successfully: notice
Syslog priority to use when user authenticates unsuccessfully: alert
Send mail if the user is not in sudoers
Use a separate timestamp for each user/tty combo
Lecture user the first time they run sudo
Root may run sudo
Allow some information gathering to give useful error messages
Require fully-qualified hostnames in the sudoers file
Visudo will honor the EDITOR environment variable
Set the LOGNAME and USER environment variables
Length at which to wrap log file lines (0 for no wrap): 80
Authentication timestamp timeout: 15.0 minutes
Password prompt timeout: 0.0 minutes
Number of tries to enter a password: 3
Umask to use or 0777 to use user's: 022
Path to mail program: /usr/sbin/sendmail
Flags for mail program: -t
Address to send mail to: root
Subject line for mail messages: *** SECURITY information for %h ***
Incorrect password message: Sorry, try again.
Path to authentication timestamp dir: /var/lib/sudo
Default password prompt: [sudo] password for %p: 
Default user to run commands as: root
Value to override user's $PATH with: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Path to the editor for use by visudo: /usr/bin/editor
When to require a password for 'list' pseudocommand: any
When to require a password for 'verify' pseudocommand: all
File descriptors >= 3 will be closed before executing a command
Environment variables to check for sanity:
	TZ
	TERM
	LINGUAS
	LC_*
	LANGUAGE
	LANG
	COLORTERM
Environment variables to remove:
	RUBYOPT
	RUBYLIB
	PYTHONUSERBASE
	PYTHONINSPECT
	PYTHONPATH
	PYTHONHOME
	TMPPREFIX
	ZDOTDIR
	READNULLCMD
	NULLCMD
	FPATH
	PERL5DB
	PERL5OPT
	PERL5LIB
	PERLLIB
	PERLIO_DEBUG 
	JAVA_TOOL_OPTIONS
	SHELLOPTS
	GLOBIGNORE
	PS4
	BASH_ENV
	ENV
	TERMCAP
	TERMPATH
	TERMINFO_DIRS
	TERMINFO
	_RLD*
	LD_*
	PATH_LOCALE
	NLSPATH
	HOSTALIASES
	RES_OPTIONS
	LOCALDOMAIN
	CDPATH
	IFS
Environment variables to preserve:
	JAVA_HOME
	TRAVIS
	CI
	DEBIAN_FRONTEND
	XAUTHORIZATION
	XAUTHORITY
	PS2
	PS1
	PATH
	LS_COLORS
	KRB5CCNAME
	HOSTNAME
	HOME
	DISPLAY
	COLORS
Locale to use while parsing sudoers: C
Directory in which to store input/output logs: /var/log/sudo-io
File in which to store the input/output log: %{seq}
Add an entry to the utmp/utmpx file when allocating a pty
PAM service name to use
PAM service name to use for login shells
Create a new PAM session for the command to run in
Maximum I/O log sequence number: 0
Local IP address and netmask pairs:
	172.17.0.2/255.255.0.0
Sudoers I/O plugin version 1.8.9p5
gzip version
gzip 1.6
Copyright (C) 2007, 2010, 2011 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
Written by Jean-loup Gailly.
zip version
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
This is Zip 3.0 (July 5th 2008), by Info-ZIP.
Currently maintained by E. Gordon.  Please send bug reports to
the authors using the web page at www.info-zip.org; see README for details.
Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip,
as of above date; see http://www.info-zip.org/ for other sites.
Compiled with gcc 4.8.2 for Unix (Linux ELF) on Oct 21 2013.
Zip special compilation options:
	USE_EF_UT_TIME       (store Universal Time)
	BZIP2_SUPPORT        (bzip2 library version 1.0.6, 6-Sept-2010)
	    bzip2 code and library copyright (c) Julian R Seward
	    (See the bzip2 license for terms of use)
	SYMLINK_SUPPORT      (symbolic links supported)
	LARGE_FILE_SUPPORT   (can read and write large files on file system)
	ZIP64_SUPPORT        (use Zip64 to store large files in archives)
	UNICODE_SUPPORT      (store and read UTF-8 Unicode paths)
	STORE_UNIX_UIDs_GIDs (store UID/GID sizes/values using new extra field)
	UIDGID_NOT_16BIT     (old Unix 16-bit UID/GID extra field not used)
	[encryption, version 2.91 of 05 Jan 2007] (modified for Zip 3)
Encryption notice:
	The encryption code of this program is not copyrighted and is
	put in the public domain.  It was originally written in Europe
	and, to the best of our knowledge, can be freely distributed
	in both source and object forms from any country, including
	the USA under License Exception TSU of the U.S. Export
	Administration Regulations (section 740.13(e)) of 6 June 2002.
Zip environment options:
             ZIP:  [none]
          ZIPOPT:  [none]
vim version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:43:18)
Included patches: 1-52
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl    -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions      
iptables version
iptables v1.4.21
curl version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
wget version
GNU Wget 1.15 built on linux-gnu.
rsync version
rsync  version 3.1.0  protocol version 31
gimme version
v1.2.0
nvm version
0.33.6
perlbrew version
/home/travis/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.80
phpenv version
rbenv 1.1.1-25-g6aa70b6
rvm version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
default ruby version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
CouchDB version
couchdb 1.6.1
ElasticSearch version
5.5.0
Installed Firefox version
firefox 56.0.2
MongoDB version
MongoDB 3.4.10
PhantomJS version
2.1.1
Pre-installed PostgreSQL versions
9.2.24
9.3.20
9.4.15
9.5.10
9.6.6
RabbitMQ Version
3.6.14
Redis version
redis-server 4.0.6
riak version
2.2.3
Pre-installed Go versions
1.7.4
ant version
Apache Ant(TM) version 1.9.3 compiled on April 8 2014
mvn version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T07:58:13Z)
Maven home: /usr/local/maven-3.5.2
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-101-generic", arch: "amd64", family: "unix"
gradle version
------------------------------------------------------------
Gradle 4.0.1
------------------------------------------------------------
Build time:   2017-07-07 14:02:41 UTC
Revision:     38e5dc0f772daecca1d2681885d3d85414eb6826
Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.4.0-101-generic amd64
lein version
Leiningen 2.8.1 on Java 1.8.0_151 Java HotSpot(TM) 64-Bit Server VM
Pre-installed Node.js versions
v4.8.6
v6.12.0
v6.12.1
v8.9
v8.9.1
phpenv versions
  system
  5.6
* 5.6.32 (set by /home/travis/.phpenv/version)
  7.0
  7.0.25
  7.1
  7.1.11
  hhvm
  hhvm-stable
composer --version
Composer version 1.5.2 2017-09-11 16:59:25
Pre-installed Ruby versions
ruby-2.2.7
ruby-2.3.4
ruby-2.4.1
Network availability confirmed.
git.checkout
2.85s$ git clone --depth=50 --branch=master https://github.com/rg3/youtube-dl.git rg3/youtube-dl
Cloning into 'rg3/youtube-dl'...
remote: Counting objects: 1189, done.
remote: Compressing objects: 100% (1013/1013), done.
remote: Total 1189 (delta 218), reused 402 (delta 170), pack-reused 0
Receiving objects: 100% (1189/1189), 1.74 MiB | 11.23 MiB/s, done.
Resolving deltas: 100% (218/218), done.
$ cd rg3/youtube-dl
$ git checkout -qf 49128b5032eba2f01ff59c2adac8ce159f6bf9f9
Setting environment variables from .travis.yml
$ export YTDL_TEST_SET=core
0.01s$ source ~/virtualenv/python3.6/bin/activate
$ python --version
Python 3.6.3
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (python 3.6)
before_install
0.00s$ if [ "$JYTHON" == "true" ]; then ./devscripts/install_jython.sh; export PATH="$HOME/jython/bin:$PATH"; fi
Could not locate requirements.txt. Override the install: key in your .travis.yml to install dependencies.
4.05s$ ./devscripts/run_tests.sh
Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters') ... ERROR
Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters') ... ERROR
test_cbc_decrypt (test.test_aes.TestAES) ... ok
test_cbc_encrypt (test.test_aes.TestAES) ... ok
test_decrypt_text (test.test_aes.TestAES) ... ok
test_encrypt (test.test_aes.TestAES) ... ok
Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters') ... ERROR
Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters') ... ERROR
test_all_present (test.test_compat.TestCompat) ... ERROR
test_compat_etree_fromstring (test.test_compat.TestCompat) ... ok
test_compat_etree_fromstring_doctype (test.test_compat.TestCompat) ... ok
test_compat_expanduser (test.test_compat.TestCompat) ... ok
test_compat_getenv (test.test_compat.TestCompat) ... ok
test_compat_setenv (test.test_compat.TestCompat) ... ok
test_compat_shlex_split (test.test_compat.TestCompat) ... ok
test_compat_urllib_parse_unquote (test.test_compat.TestCompat) ... ok
test_compat_urllib_parse_unquote_plus (test.test_compat.TestCompat) ... ok
test_compat_urllib_parse_urlencode (test.test_compat.TestCompat) ... ok
test_struct_unpack (test.test_compat.TestCompat) ... ok
Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters') ... ERROR
test_cmdline_umlauts (test.test_execution.TestExecution) ... FAIL
test_import (test.test_execution.TestExecution) ... Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
ERROR
test_main_exec (test.test_execution.TestExecution) ... Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "youtube_dl/__main__.py", line 16, in <module>
    import youtube_dl
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
ERROR
test_module_exec (test.test_execution.TestExecution) ... Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
ERROR
Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters') ... ERROR
test_array_access (test.test_jsinterp.TestJSInterpreter) ... ok
test_assignments (test.test_jsinterp.TestJSInterpreter) ... ok
test_basic (test.test_jsinterp.TestJSInterpreter) ... ok
test_calc (test.test_jsinterp.TestJSInterpreter) ... ok
test_call (test.test_jsinterp.TestJSInterpreter) ... ok
Skipping: Not yet fully implemented ... ok
test_empty_return (test.test_jsinterp.TestJSInterpreter) ... ok
test_morespace (test.test_jsinterp.TestJSInterpreter) ... ok
test_operators (test.test_jsinterp.TestJSInterpreter) ... ok
test_parens (test.test_jsinterp.TestJSInterpreter) ... ok
test_precedence (test.test_jsinterp.TestJSInterpreter) ... ok
test_strange_chars (test.test_jsinterp.TestJSInterpreter) ... ok
Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters') ... ERROR
test_hide_login_info (test.test_options.TestOptions) ... ok
test_format_to_regex (test.test_postprocessors.TestMetadataFromTitle) ... ok
test_swf_ArrayAccess (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_ClassCall (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_ClassConstruction (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_ConstArrayAccess (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_ConstantInt (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_DictCall (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_EqualsOperator (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_LocalVars (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_MemberAssignment (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_NeOperator (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_PrivateCall (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_PrivateVoidCall (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_StaticAssignment (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_StaticRetrieval (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_StringBasics (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_StringCharCodeAt (test.test_swfinterp.TestSWFInterpreter) ... ok
test_swf_StringConversion (test.test_swfinterp.TestSWFInterpreter) ... ok
Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters') ... ERROR
test_rsa_verify (test.test_update.TestUpdate) ... ok
test_age_restricted (test.test_utils.TestUtil) ... ok
test_args_to_str (test.test_utils.TestUtil) ... ok
test_base_url (test.test_utils.TestUtil) ... ok
test_clean_html (test.test_utils.TestUtil) ... ok
test_cli_bool_option (test.test_utils.TestUtil) ... ok
test_cli_option (test.test_utils.TestUtil) ... ok
test_cli_valueless_option (test.test_utils.TestUtil) ... ok
test_date_from_str (test.test_utils.TestUtil) ... ok
test_daterange (test.test_utils.TestUtil) ... ok
test_detect_exe_version (test.test_utils.TestUtil) ... ok
test_determine_ext (test.test_utils.TestUtil) ... ok
test_dfxp2srt (test.test_utils.TestUtil) ... ok
test_dict_get (test.test_utils.TestUtil) ... ok
test_encode_base_n (test.test_utils.TestUtil) ... ok
test_encode_compat_str (test.test_utils.TestUtil) ... ok
test_escape_rfc3986 (test.test_utils.TestUtil) ... ok
test_escape_url (test.test_utils.TestUtil) ... ok
test_expand_path (test.test_utils.TestUtil) ... ok
test_extract_attributes (test.test_utils.TestUtil) ... ok
test_find_xpath_attr (test.test_utils.TestUtil) ... ok
test_fix_xml_ampersands (test.test_utils.TestUtil) ... ok
test_get_element_by_attribute (test.test_utils.TestUtil) ... ok
test_get_element_by_class (test.test_utils.TestUtil) ... ok
test_get_elements_by_attribute (test.test_utils.TestUtil) ... ok
test_get_elements_by_class (test.test_utils.TestUtil) ... ok
test_intlist_to_bytes (test.test_utils.TestUtil) ... ok
test_is_html (test.test_utils.TestUtil) ... ok
test_js_to_json_edgecases (test.test_utils.TestUtil) ... ok
test_js_to_json_malformed (test.test_utils.TestUtil) ... ok
test_js_to_json_realworld (test.test_utils.TestUtil) ... ok
test_limit_length (test.test_utils.TestUtil) ... ok
test_lowercase_escape (test.test_utils.TestUtil) ... ok
test_match_str (test.test_utils.TestUtil) ... ok
test_merge_dicts (test.test_utils.TestUtil) ... ok
test_mimetype2ext (test.test_utils.TestUtil) ... ok
test_month_by_name (test.test_utils.TestUtil) ... ok
test_multipart_encode (test.test_utils.TestUtil) ... ok
test_ohdave_rsa_encrypt (test.test_utils.TestUtil) ... ok
test_ordered_set (test.test_utils.TestUtil) ... ok
test_paged_list (test.test_utils.TestUtil) ... ok
test_parse_age_limit (test.test_utils.TestUtil) ... ok
test_parse_codecs (test.test_utils.TestUtil) ... WARNING: Unknown codec newcodec
ok
test_parse_count (test.test_utils.TestUtil) ... ok
test_parse_dfxp_time_expr (test.test_utils.TestUtil) ... ok
test_parse_duration (test.test_utils.TestUtil) ... ok
test_parse_filesize (test.test_utils.TestUtil) ... ok
test_parse_iso8601 (test.test_utils.TestUtil) ... ok
test_parse_resolution (test.test_utils.TestUtil) ... ok
test_pkcs1pad (test.test_utils.TestUtil) ... ok
test_prepend_extension (test.test_utils.TestUtil) ... ok
test_read_batch_urls (test.test_utils.TestUtil) ... ok
test_remove_end (test.test_utils.TestUtil) ... ok
test_remove_quotes (test.test_utils.TestUtil) ... ok
test_remove_start (test.test_utils.TestUtil) ... ok
test_render_table (test.test_utils.TestUtil) ... ok
test_replace_extension (test.test_utils.TestUtil) ... ok
test_sanitize_filename (test.test_utils.TestUtil) ... ok
test_sanitize_filename_restricted (test.test_utils.TestUtil) ... ok
test_sanitize_ids (test.test_utils.TestUtil) ... ok
test_sanitize_path (test.test_utils.TestUtil) ... ok
test_sanitize_url (test.test_utils.TestUtil) ... ok
test_shell_quote (test.test_utils.TestUtil) ... ok
test_smuggle_url (test.test_utils.TestUtil) ... ok
test_str_to_int (test.test_utils.TestUtil) ... ok
test_strip_jsonp (test.test_utils.TestUtil) ... ok
test_timeconvert (test.test_utils.TestUtil) ... ok
test_unescape_html (test.test_utils.TestUtil) ... ok
test_unified_dates (test.test_utils.TestUtil) ... ok
test_unified_timestamps (test.test_utils.TestUtil) ... ok
test_update_url_query (test.test_utils.TestUtil) ... ok
test_uppercase_escape (test.test_utils.TestUtil) ... ok
test_url_basename (test.test_utils.TestUtil) ... ok
test_urlencode_postdata (test.test_utils.TestUtil) ... ok
test_urljoin (test.test_utils.TestUtil) ... ok
test_urshift (test.test_utils.TestUtil) ... ok
test_version_tuple (test.test_utils.TestUtil) ... ok
test_xpath_attr (test.test_utils.TestUtil) ... ok
test_xpath_element (test.test_utils.TestUtil) ... ok
test_xpath_text (test.test_utils.TestUtil) ... ok
test_xpath_with_ns (test.test_utils.TestUtil) ... ok
test_private_info_arg (test.test_verbose_output.TestVerboseOutput) ... FAIL
test_private_info_eq (test.test_verbose_output.TestVerboseOutput) ... FAIL
test_private_info_shortarg (test.test_verbose_output.TestVerboseOutput) ... FAIL
test_private_info_shortarg_eq (test.test_verbose_output.TestVerboseOutput) ... FAIL
Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters') ... ERROR
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/rg3/youtube-dl/test/test_InfoExtractor.py", line 12, in <module>
    from test.helper import FakeYDL, expect_dict, expect_value
  File "/home/travis/build/rg3/youtube-dl/test/helper.py", line 12, in <module>
    import youtube_dl.extractor
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/rg3/youtube-dl/test/test_YoutubeDL.py", line 14, in <module>
    from test.helper import FakeYDL, assertRegexpMatches
  File "/home/travis/build/rg3/youtube-dl/test/helper.py", line 12, in <module>
    import youtube_dl.extractor
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/rg3/youtube-dl/test/test_all_urls.py", line 13, in <module>
    from test.helper import gettestcases
  File "/home/travis/build/rg3/youtube-dl/test/helper.py", line 12, in <module>
    import youtube_dl.extractor
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/rg3/youtube-dl/test/test_cache.py", line 15, in <module>
    from test.helper import FakeYDL
  File "/home/travis/build/rg3/youtube-dl/test/helper.py", line 12, in <module>
    import youtube_dl.extractor
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
======================================================================
ERROR: test_all_present (test.test_compat.TestCompat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/test/test_compat.py", line 48, in test_all_present
    import youtube_dl.compat
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/rg3/youtube-dl/test/test_downloader_http.py", line 12, in <module>
    from test.helper import try_rm
  File "/home/travis/build/rg3/youtube-dl/test/helper.py", line 12, in <module>
    import youtube_dl.extractor
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
======================================================================
ERROR: test_import (test.test_execution.TestExecution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/test/test_execution.py", line 26, in test_import
    subprocess.check_call([sys.executable, '-c', 'import youtube_dl'], cwd=rootDir)
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/travis/virtualenv/python3.6.3/bin/python', '-c', 'import youtube_dl']' returned non-zero exit status 1.
======================================================================
ERROR: test_main_exec (test.test_execution.TestExecution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/test/test_execution.py", line 33, in test_main_exec
    subprocess.check_call([sys.executable, 'youtube_dl/__main__.py', '--version'], cwd=rootDir, stdout=_DEV_NULL)
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/travis/virtualenv/python3.6.3/bin/python', 'youtube_dl/__main__.py', '--version']' returned non-zero exit status 1.
======================================================================
ERROR: test_module_exec (test.test_execution.TestExecution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/test/test_execution.py", line 30, in test_module_exec
    subprocess.check_call([sys.executable, '-m', 'youtube_dl', '--version'], cwd=rootDir, stdout=_DEV_NULL)
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/travis/virtualenv/python3.6.3/bin/python', '-m', 'youtube_dl', '--version']' returned non-zero exit status 1.
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/rg3/youtube-dl/test/test_http.py", line 11, in <module>
    from youtube_dl import YoutubeDL
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/rg3/youtube-dl/test/test_netrc.py", line 10, in <module>
    from youtube_dl.extractor import (
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/rg3/youtube-dl/test/test_unicode_literals.py", line 25, in <module>
    from test.helper import assertRegexpMatches
  File "/home/travis/build/rg3/youtube-dl/test/helper.py", line 12, in <module>
    import youtube_dl.extractor
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'youtube_dl.extractor.frontendmasters')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/rg3/youtube-dl/test/test_youtube_chapters.py", line 11, in <module>
    from test.helper import expect_value
  File "/home/travis/build/rg3/youtube-dl/test/helper.py", line 12, in <module>
    import youtube_dl.extractor
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>
    from .frontendmasters import (
ModuleNotFoundError: No module named 'youtube_dl.extractor.frontendmasters'
======================================================================
FAIL: test_cmdline_umlauts (test.test_execution.TestExecution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/test/test_execution.py", line 40, in test_cmdline_umlauts
    self.assertFalse(stderr)
AssertionError: b'Traceback (most recent call last):\n  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>\n    from .lazy_extractors import *\nModuleNotFoundError: No module named \'youtube_dl.extractor.lazy_extractors\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "youtube_dl/__main__.py", line 16, in <module>\n    import youtube_dl\n  File "/home/travis/build/rg3/youtube-dl/youtube_dl/__init__.py", line 43, in <module>\n    from .extractor import gen_extractors, list_extractors\n  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>\n    from .extractors import *\n  File "/home/travis/build/rg3/youtube-dl/youtube_dl/extractor/extractors.py", line 393, in <module>\n    from .frontendmasters import (\nModuleNotFoundError: No module named \'youtube_dl.extractor.frontendmasters\'\n' is not false
======================================================================
FAIL: test_private_info_arg (test.test_verbose_output.TestVerboseOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/test/test_verbose_output.py", line 25, in test_private_info_arg
    self.assertTrue(b'--username' in serr)
AssertionError: False is not true
======================================================================
FAIL: test_private_info_eq (test.test_verbose_output.TestVerboseOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/test/test_verbose_output.py", line 51, in test_private_info_eq
    self.assertTrue(b'--username' in serr)
AssertionError: False is not true
======================================================================
FAIL: test_private_info_shortarg (test.test_verbose_output.TestVerboseOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/test/test_verbose_output.py", line 38, in test_private_info_shortarg
    self.assertTrue(b'-u' in serr)
AssertionError: False is not true
======================================================================
FAIL: test_private_info_shortarg_eq (test.test_verbose_output.TestVerboseOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rg3/youtube-dl/test/test_verbose_output.py", line 64, in test_private_info_shortarg_eq
    self.assertTrue(b'-u' in serr)
AssertionError: False is not true
----------------------------------------------------------------------
Ran 144 tests in 2.858s
FAILED (errors=13, failures=5)
The command "./devscripts/run_tests.sh" exited with 1.
Done. Your build exited with 1.
Top
©TRAVIS CI, GMBH
Rigaer Straße 8
10247 Berlin, Germany
Work with Travis CI
Blog
Email
Twitter
HELP
Documentation
Community
Changelog
LEGAL
Imprint
Terms of Service
Privacy Policy
Security Statement
TRAVIS CI STATUS
Status: Travis CI Status